version: '3'

services:
  db:
    image: mongo:4.2
    env_file:
      - ./.env
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - '27017:27017'
  api:
    depends_on:
      - db
    links:
      - db
    image: node:18-alpine
    env_file:
      - ./.env
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    working_dir: /app
    volumes:
      - ./:/app
    command: ['sh', '-c', 'yarn && yarn start:dev']
